### ISSUE TITLE
Lightning network support

### ISSUE THREAD

**Issue by tiedtoastar** [MrNaif2018/bitcart-sdk#1]
Implement support for the bitcoin lightning network

**Comment by MrNaif2018** [comment]
Hello! Yesterday I have implemented that, check out docs at sdk.bitcartcc.com
I will update docs with some examples soon, but you can use api documentation too:
sdk.bitcartcc.com/en/latest/api.html

**Comment by MrNaif2018** [comment]
Also take a look at MrNaif2018/bitcart#51 for some instructions how to start daemons after new update

**Comment by MrNaif2018** [comment]
Did it help you @tiedtoastar?

**Comment by MrNaif2018** [comment]
Closing this for now, will add more docs soon, also check out new usage example in examples/ folder of the repo.
